#Sakhawat Hossain Rabbi

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostClassifier,RandomForestRegressor,RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/content/test (1).csv')

In [ ]:
df.head(10)

UEI                 Company Name            PIID        IDVPIID  \
0  F8G4FTQNUZT7      BRAVIUM CONSULTING INC.  75ACF121F80002     GS35F461CA   
1  QHBLBNKKV4U3     ICF INCORPORATED, L.L.C.  75ACF122F80053     GS00F010CA   
2  QHBLBNKKV4U3     ICF INCORPORATED, L.L.C.  75ACF122F80021     GS00F010CA   
3  QHBLBNKKV4U3     ICF INCORPORATED, L.L.C.  75ACF122F80037     GS00F010CA   
4  GPV8EN61NBN6     INFO GAIN CONSULTING LLC  75ACF122C00023            NaN   
5  VNAYDLRGSKU3        URBAN INSTITUTE (THE)  75ACF121F80036  47QRAA18D003Z   
6  LE1MCXJEQGK8          MEF ASSOCIATES, LLC  75ACF121F80031  47QRAA19D00DK   
7  SRG2J1WS9X63            SRI INTERNATIONAL  75ACF121F80032  47QRAA21D002R   
8  JJHCMK4NT5N3  RESEARCH TRIANGLE INSTITUTE  75ACF122F80038     GS00F354CA   
9  DMHDNDCPWUD1        THE MITRE CORPORATION  75ACF122F80033  75FCMC18D0047   

                                     Agency  \
0  Administration for Children and Families   
1  Administration for Children and Families   
2  Administration for Children and Families   
3  Administration for Children and Families   
4  Administration for Children and Families   
5  Administration for Children and Families   
6  Administration for Children and Families   
7  Administration for Children and Families   
8  Administration for Children and Families   
9  Administration for Children and Families   

                                       Contract Desc Set Aside  \
0  SERVICENOW SOFTWARE LICENSE SUBSCRIPTIONS FOR ...        8A   
1  LOW INCOME HOME ENERGY ASSISTANCE PROGRAM  (LI...       NaN   
2  STATE CAPACITY BUILDING CENTER TECHNICAL ASSIS...       NaN   
3  THIS TASK ORDER IS INTENDED TO PROCURE A WIDE ...       NaN   
4  COMMUNITY ECONOMIC DEVELOPMENT (CED) GRANT PRO...       8AN   
5  ADVANCING CONTEXTUAL ANALYSIS AND METHODS OF P...       NaN   
6  THE CONTRACTOR SHALL PROVIDE ALL PERSONNEL, EQ...       SBA   
7  ACF DATA GOVERNANCE CONSULTING AND SUPPORT EXT...       NaN   
8  ADOLESCENT DEVELOPMENT PRODUCTS AND THE WE THI...       NaN   
9  TRAINING AND TECHNICAL ASSISTANCE STRATEGY: ST...       NaN   

                                Principal Naics Code    Contract Pricing  \
0            541512-Computer Systems Design Services         Fixed Price   
1  541611-Administrative Management and General M...         Fixed Price   
2  541611-Administrative Management and General M...         Fixed Price   
3  541611-Administrative Management and General M...  Time and Materials   
4  541611-Administrative Management and General M...         Fixed Price   
5  541611-Administrative Management and General M...  Time and Materials   
6  541611-Administrative Management and General M...  Time and Materials   
7  541611-Administrative Management and General M...  Time and Materials   
8  541611-Administrative Management and General M...         Fixed Price   
9  541990-All Other Professional, Scientific, and...         Fixed Price   

            Contract Date    Contract Expiry Date  Obligated Amount POP state  
0  10/30/2020 12:00:00 AM  10/31/2025 12:00:00 AM            264562        MD  
1  09/30/2022 12:00:00 AM  09/29/2025 12:00:00 AM            871819        DC  
2  09/29/2022 12:00:00 AM  09/29/2025 12:00:00 AM          13214685        VA  
3  09/28/2022 12:00:00 AM  09/29/2025 12:00:00 AM           1239525        VA  
4  09/06/2022 12:00:00 AM  09/29/2025 12:00:00 AM            203480        DC  
5  09/27/2021 12:00:00 AM  09/29/2025 12:00:00 AM           1643484        DC  
6  09/22/2021 12:00:00 AM  09/29/2025 12:00:00 AM           1094728        VA  
7  09/19/2021 12:00:00 AM  09/29/2025 12:00:00 AM            693611        DC  
8  09/22/2022 12:00:00 AM  09/27/2025 12:00:00 AM           1396697        DC  
9  09/23/2022 12:00:00 AM  08/30/2025 12:00:00 AM            214998        VA

In [ ]:
df.tail

<bound method NDFrame.tail of                 UEI                                   Company Name  \
0      F8G4FTQNUZT7                        BRAVIUM CONSULTING INC.   
1      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
2      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
3      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
4      GPV8EN61NBN6                       INFO GAIN CONSULTING LLC   
...             ...                                            ...   
17768  HKS1BN6QXJ95                             IQ SOLUTIONS, INC.   
17769  NACNDU85S2Q2                        JBS INTERNATIONAL, INC.   
17770  K3RCJNRN5T46                      MAYATECH CORPORATION, THE   
17771  DMHDNDCPWUD1                          THE MITRE CORPORATION   
17772  S954U5F3LLS9  VANGUARD COMMUNICATIONS OF FALLS CHURCH, INC.   

                 PIID            IDVPIID  \
0      75ACF121F80002         GS35F461CA   
1      75ACF122F80053         GS00F010CA 

In [ ]:
df.shape

(17773, 13)

In [ ]:
df.info

<bound method DataFrame.info of                 UEI                                   Company Name  \
0      F8G4FTQNUZT7                        BRAVIUM CONSULTING INC.   
1      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
2      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
3      QHBLBNKKV4U3                       ICF INCORPORATED, L.L.C.   
4      GPV8EN61NBN6                       INFO GAIN CONSULTING LLC   
...             ...                                            ...   
17768  HKS1BN6QXJ95                             IQ SOLUTIONS, INC.   
17769  NACNDU85S2Q2                        JBS INTERNATIONAL, INC.   
17770  K3RCJNRN5T46                      MAYATECH CORPORATION, THE   
17771  DMHDNDCPWUD1                          THE MITRE CORPORATION   
17772  S954U5F3LLS9  VANGUARD COMMUNICATIONS OF FALLS CHURCH, INC.   

                 PIID            IDVPIID  \
0      75ACF121F80002         GS35F461CA   
1      75ACF122F80053         GS00F010C

In [ ]:
df.isnull().sum()

UEI                        0
Company Name               0
PIID                       0
IDVPIID                 6013
Agency                     0
Contract Desc              1
Set Aside               9961
Principal Naics Code       0
Contract Pricing           0
Contract Date              0
Contract Expiry Date       0
Obligated Amount           0
POP state                214
dtype: int64

In [ ]:
df.isnull().mean()*100

UEI                      0.000000
Company Name             0.000000
PIID                     0.000000
IDVPIID                 33.832217
Agency                   0.000000
Contract Desc            0.005627
Set Aside               56.045687
Principal Naics Code     0.000000
Contract Pricing         0.000000
Contract Date            0.000000
Contract Expiry Date     0.000000
Obligated Amount         0.000000
POP state                1.204074
dtype: float64

In [ ]:
# Handle missing values by filling with the most frequent value in each column
columns_with_missing_values = ['IDVPIID', 'Contract Desc', 'Set Aside', 'POP state']

for column in columns_with_missing_values:
    most_frequent_value = df[column].mode()[0]
    df[column].fillna(most_frequent_value, inplace=True)


In [ ]:
df.isnull().sum()

UEI                     0
Company Name            0
PIID                    0
IDVPIID                 0
Agency                  0
Contract Desc           0
Set Aside               0
Principal Naics Code    0
Contract Pricing        0
Contract Date           0
Contract Expiry Date    0
Obligated Amount        0
POP state               0
dtype: int64

In [ ]:
df.duplicated().sum()

122

In [ ]:
#check for duplicates is 'UEI'
duplicates_in_uei = df[df.duplicated(subset='UEI', keep=False)]


print(duplicates_in_uei)

        UEI  Company Name   PIID  IDVPIID  Agency  Contract Desc  Set Aside  \
1      3125          2082    373     1801       0           8091          7   
2      3125          2082    357     1801       0          13295          7   
3      3125          2082    365     1801       0          15006          7   
4      1173          2160    345     2979       0           2938          1   
5      3846          4457    334       70       0            627          7   
...     ...           ...    ...      ...     ...            ...        ...   
17767  2981           576  12052     2918      12           7004          8   
17768  1392          2268  12036     3106      12          12499          7   
17769  2687          2329  12031     3107      12           6202          7   
17770  1815          2680  12031     3112      12           6761          7   
17771   405          4194  12050      680      12          12500          7   

       Principal Naics Code  Contract Pricing  Cont

In [ ]:
# identify duplicated rows
duplicates = df[df.duplicated(keep=False)]

# Fill null values in the duplicated rows with the corresponding non-null values
df_filled_duplicates = duplicates.fillna(method='ffill')

# Update the original DataFrame with the filled duplicate rows
df.update(df_filled_duplicates)


In [ ]:
# Encoding categorical variables using Label Encoding
label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    label_encoders[column] = LabelEncoder()
    df[column] = label_encoders[column].fit_transform(df[column])

# Print the encoding data for each column
for column, encoder in label_encoders.items():
    print(f"Label Encoding for {column}: {dict(zip(encoder.classes_, encoder.transform(encoder.classes_)))}")

# Print the updated DataFrame with encoded categorical variables
print(df)


In [ ]:
# Perform one-hot encoding on categorical columns
df_encoded = pd.get_dummies(df, columns=df.select_dtypes(include=['object']).columns)

# Print the updated DataFrame with one-hot encoded categorical variables
print(df_encoded)

        UEI  Company Name   PIID  IDVPIID  Agency  Contract Desc  Set Aside  \
0       798           720    322     2414       0          12927          0   
1      3125          2082    373     1801       0           8091          7   
2      3125          2082    357     1801       0          13295          7   
3      3125          2082    365     1801       0          15006          7   
4      1173          2160    345     2979       0           2938          1   
...     ...           ...    ...      ...     ...            ...        ...   
17768  1392          2268  12036     3106      12          12499          7   
17769  2687          2329  12031     3107      12           6202          7   
17770  1815          2680  12031     3112      12           6761          7   
17771   405          4194  12050      680      12          12500          7   
17772  3353          4478  12548     3113      12          15569          7   

       Principal Naics Code  Contract Pricing  Cont

In [ ]:
df.columns

Index(['UEI', 'Company Name', 'PIID', 'IDVPIID', 'Agency', 'Contract Desc',
       'Set Aside', 'Principal Naics Code', 'Contract Pricing',
       'Contract Date', 'Contract Expiry Date', 'Obligated Amount',
       'POP state'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)



#Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler


X = df_encoded.drop(columns=['UEI', 'Company Name', 'PIID', 'IDVPIID', 'Contract Desc', 'Contract Date', 'Contract Expiry Date'])
y = df_encoded['Obligated Amount']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Scaled Features (X_scaled):")
print(X_scaled)


Scaled Features (X_scaled):
[[-3.00846095 -4.70497039  0.20269802 -0.26733371 -0.09085964 -0.20317275]
 [-3.00846095  0.15754889  0.24242036 -0.26733371 -0.04337779 -1.23006384]
 [-3.00846095  0.15754889  0.24242036 -0.26733371  0.92171947  1.77726009]
 ...
 [ 3.22273538  0.15754889  0.507236   -1.44291856 -0.0620086  -0.20317275]
 [ 3.22273538  0.15754889  0.507236   -1.05105695 -0.06916633  1.77726009]
 [ 3.22273538  0.15754889  0.507236   -1.44291856  0.0829191  -1.23006384]]


In [ ]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Splitting Data into Features and Target Variable
X = df.drop(columns=['UEI', 'Contract Expiry Date', 'POP state'])
y = df['POP state']


In [ ]:
# Splitting Data into Training and Testing Sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



In [ ]:
# Build and evaluate the ensemble models
models = {
    "Random Forest": RandomForestClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "SVM": SVC(random_state=42),
    "XGBoost": XGBClassifier(random_state=42)
}

In [ ]:
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {accuracy:.2f}")

Random Forest Accuracy: 0.66
AdaBoost Accuracy: 0.40
Decision Tree Accuracy: 0.55
SVM Accuracy: 0.37
XGBoost Accuracy: 0.65
